<a href="https://colab.research.google.com/github/Rajesh1215/Breast_cancer_detection_tensorflow/blob/main/Medical.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/

In [ ]:
!kaggle datasets download -d paultimothymooney/breast-histopathology-images

100% 3.08G/3.10G [00:35<00:00, 39.6MB/s]
100% 3.10G/3.10G [00:35<00:00, 92.8MB/s]


In [ ]:
import zipfile
zip_ref = zipfile.ZipFile('/content/breast-histopathology-images.zip', 'r')
zip_ref.extractall('/content')
zip_ref.close()

In [ ]:
import tensorflow as tf
from tensorflow import keras
from keras import layers, models,Sequential
from keras.layers import Dense,MaxPool2D,Flatten,Conv2D,Input,MaxPooling2D,BatchNormalization,Dropout
from tensorflow.keras.utils import image_dataset_from_directory
from tensorflow.keras.models import Model
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import os

# Specify the directory path you want to examine



In [ ]:
directory_path = '/content/IDC_regular_ps50_idx5'  # Replace with your specific path

# Get a list of all directories in the specified path
directories = [d for d in os.listdir(directory_path) if os.path.isdir(os.path.join(directory_path, d))]

# Print the list of directories
# print("List of directories:")
# for directory in directories:
#     print(directory)
len(directories)

279

In [ ]:
import tensorflow as tf
import os

# Directory path containing subdirectories
directory_path = '/content/IDC_regular_ps50_idx5'  # Replace with your specific path

# Get a list of all directories (subdirectories) within the specified path
subdirectories = [d for d in os.listdir(directory_path) if os.path.isdir(os.path.join(directory_path, d))]

# Create an empty list to store datasets
datasets = []

# Iterate through subdirectories
for subdir in subdirectories:
    subdir_path = os.path.join(directory_path, subdir)

    # Use image_dataset_from_directory to create a labeled dataset
    dataset = tf.keras.utils.image_dataset_from_directory(
        directory=subdir_path,
        labels="inferred",
        label_mode="int",
        class_names=None,
        color_mode="rgb",
        batch_size=32,  # You can adjust the batch size
        image_size=(256, 256),  # Adjust image size as needed
        shuffle=True,
    )

    # Assign labels based on folder names

    # Append the dataset to the list
    datasets.append(dataset)

# Now, 'datasets' is a list of datasets, each containing images and labels for each subdirectory.


Found 761 files belonging to 2 classes.
Found 483 files belonging to 2 classes.
Found 861 files belonging to 2 classes.
Found 517 files belonging to 2 classes.
Found 610 files belonging to 2 classes.
Found 1197 files belonging to 2 classes.
Found 2004 files belonging to 2 classes.
Found 1399 files belonging to 2 classes.
Found 171 files belonging to 2 classes.
Found 557 files belonging to 2 classes.
Found 1623 files belonging to 2 classes.
Found 1357 files belonging to 2 classes.
Found 1326 files belonging to 2 classes.
Found 991 files belonging to 2 classes.
Found 895 files belonging to 2 classes.
Found 613 files belonging to 2 classes.
Found 1154 files belonging to 2 classes.
Found 1191 files belonging to 2 classes.
Found 1000 files belonging to 2 classes.
Found 367 files belonging to 2 classes.
Found 219 files belonging to 2 classes.
Found 635 files belonging to 2 classes.
Found 478 files belonging to 2 classes.
Found 836 files belonging to 2 classes.
Found 1510 files belonging to 2

In [ ]:
for x,z in datasets[0].take(10):
  print(z)

tf.Tensor([0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 1 0 0 0 1 0 1 0 0 0 1 0 1 0], shape=(32,), dtype=int32)
tf.Tensor([1 0 1 0 0 0 1 0 1 1 1 1 1 0 0 0 1 1 1 1 0 1 0 1 1 0 1 0 0 0 0 1], shape=(32,), dtype=int32)
tf.Tensor([0 0 1 0 0 1 0 1 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0], shape=(32,), dtype=int32)
tf.Tensor([1 0 1 1 0 1 0 0 0 1 0 0 0 1 1 0 0 1 1 0 1 1 1 1 0 0 0 0 0 0 0 1], shape=(32,), dtype=int32)
tf.Tensor([1 0 1 1 0 1 0 0 0 1 0 0 1 1 0 0 1 0 0 1 0 0 0 1 0 0 0 0 0 1 1 1], shape=(32,), dtype=int32)
tf.Tensor([1 0 0 0 0 1 0 1 0 0 0 1 1 0 0 0 0 0 1 0 1 0 0 0 0 1 1 1 0 0 0 0], shape=(32,), dtype=int32)
tf.Tensor([1 1 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0 0 1 1], shape=(32,), dtype=int32)
tf.Tensor([0 1 1 0 1 1 1 0 0 1 1 0 0 1 1 0 0 1 1 0 0 1 0 1 0 0 0 0 0 0 0 1], shape=(32,), dtype=int32)
tf.Tensor([0 0 1 0 0 0 0 1 0 1 1 1 0 0 0 0 0 0 0 0 1 0 0 1 0 0 1 0 1 1 0 0], shape=(32,), dtype=int32)
tf.Tensor([0 0 1 1 0 0 1 0 0 0 0 0 1 0 1 0 1 1 0 1 0 0 0 1 0 0 0 0 1 1 1 

In [ ]:
for i in datasets:
  print(i)


<_BatchDataset element_spec=(TensorSpec(shape=(None, 256, 256, 3), dtype=tf.float32, name=None), TensorSpec(shape=(None,), dtype=tf.int32, name=None))>
<_BatchDataset element_spec=(TensorSpec(shape=(None, 256, 256, 3), dtype=tf.float32, name=None), TensorSpec(shape=(None,), dtype=tf.int32, name=None))>
<_BatchDataset element_spec=(TensorSpec(shape=(None, 256, 256, 3), dtype=tf.float32, name=None), TensorSpec(shape=(None,), dtype=tf.int32, name=None))>
<_BatchDataset element_spec=(TensorSpec(shape=(None, 256, 256, 3), dtype=tf.float32, name=None), TensorSpec(shape=(None,), dtype=tf.int32, name=None))>
<_BatchDataset element_spec=(TensorSpec(shape=(None, 256, 256, 3), dtype=tf.float32, name=None), TensorSpec(shape=(None,), dtype=tf.int32, name=None))>
<_BatchDataset element_spec=(TensorSpec(shape=(None, 256, 256, 3), dtype=tf.float32, name=None), TensorSpec(shape=(None,), dtype=tf.int32, name=None))>
<_BatchDataset element_spec=(TensorSpec(shape=(None, 256, 256, 3), dtype=tf.float32, nam

In [ ]:
import os

def count_files_in_directory(directory):
    file_count = 0
    for root, _, files in os.walk(directory):
        file_count += len(files)
    return file_count

directory_path = '/content/12891/1'  # Replace with the actual path to the "12891" folder
total_files = count_files_in_directory(directory_path)

print(f"Total number of files in '{directory_path}' and its subfolders: {total_files}")


Total number of files in '/content/12891/1' and its subfolders: 172


In [ ]:
subdirectories

['13025',
 '9228',
 '12897',
 '9022',
 '8950',
 '13021',
 '12934',
 '9259',
 '8916',
 '13404',
 '9077',
 '13616',
 '9381',
 '9076',
 '10295',
 '8951',
 '10269',
 '13691',
 '12930',
 '16533',
 '9174',
 '10257',
 '14082',
 '9043',
 '13019',
 '14190',
 '16551',
 '13460',
 '9260',
 '14191',
 '12819',
 '12933',
 '12900',
 '9173',
 '10306',
 '12823',
 '16014',
 '9037',
 '15472',
 '12896',
 '10302',
 '12935',
 '14155',
 '9250',
 '10268',
 '15471',
 '13401',
 '12821',
 '13459',
 '9262',
 '12908',
 '12868',
 '10253',
 '16570',
 '13403',
 '9123',
 '13688',
 '9322',
 '10273',
 '9083',
 '14213',
 '12817',
 '14210',
 '14154',
 '9265',
 '9036',
 '10256',
 '14304',
 '9225',
 '16550',
 '14081',
 '16555',
 '14153',
 '10261',
 '10277',
 '9125',
 '12241',
 '8864',
 '10264',
 '12951',
 '9324',
 '9081',
 '12871',
 '12752',
 '12882',
 '14321',
 '16552',
 '13694',
 '15514',
 '12893',
 '9175',
 '12811',
 '10276',
 '9347',
 '14079',
 '16085',
 '12901',
 '12898',
 '12907',
 '9383',
 '9344',
 '9257',
 '12909',
 

In [ ]:
positive_count = 0
negative_count = 0

for batch in datasets[0]:
    labels = batch[1]

    # Count the number of positive (1) and negative (0) labels in the batch
    positive_count += tf.reduce_sum(tf.cast(labels == 1, tf.int32))
    negative_count += tf.reduce_sum(tf.cast(labels == 0, tf.int32))

print(f"Number of Positive Examples: {positive_count.numpy()}")
print(f"Number of Negative Examples: {negative_count.numpy()}")


Number of Positive Examples: 296
Number of Negative Examples: 465


In [ ]:
combined_dataset = datasets[0]
for dataset in datasets[1:]:
    combined_dataset = combined_dataset.concatenate(dataset)


In [ ]:
for i in combined_dataset.take(1):
  print(i[1])

tf.Tensor([0 1 1 1 0 0 1 1 0 0 0 1 0 1 1 1 0 0 0 1 0 1 0 0 1 0 1 0 0 0 0 1], shape=(32,), dtype=int32)


In [ ]:
model = Sequential([
    Conv2D(32, kernel_size=3, input_shape=(256, 256, 3), activation='relu'),
    MaxPooling2D(pool_size=2),
    BatchNormalization(),
    Conv2D(64, kernel_size=3, activation='relu'),
    MaxPooling2D(pool_size=2),
    BatchNormalization(),
    Conv2D(128, kernel_size=3, activation='relu'),
    MaxPooling2D(pool_size=2),
    BatchNormalization(),
    Conv2D(256, kernel_size=3, activation='relu'),
    MaxPooling2D(pool_size=2),
    BatchNormalization(),
    Conv2D(512, kernel_size=3, activation='relu'),
    MaxPooling2D(pool_size=2),
    BatchNormalization(),
    Conv2D(512, kernel_size=3, activation='relu'),
    MaxPooling2D(pool_size=2),
    BatchNormalization(),
    Flatten(),
    Dense(1024,activation="relu"),
    Dense(512,activation="relu"),
    Dense(256,activation="relu"),
    Dense(128,activation="relu"),
    Dense(64,activation="relu"),
    Dense(32,activation="relu"),
    Dense(16,activation="relu"),
    Dense(1,activation="sigmoid"),
])
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_6 (Conv2D)           (None, 254, 254, 32)      896       
                                                                 
 max_pooling2d_6 (MaxPoolin  (None, 127, 127, 32)      0         
 g2D)                                                            
                                                                 
 batch_normalization_6 (Bat  (None, 127, 127, 32)      128       
 chNormalization)                                                
                                                                 
 conv2d_7 (Conv2D)           (None, 125, 125, 64)      18496     
                                                                 
 max_pooling2d_7 (MaxPoolin  (None, 62, 62, 64)        0         
 g2D)                                                            
                                                      

In [ ]:
train_dataset = combined_dataset.skip(int(0.7 * len(combined_dataset)))  # Use 10% for validation
validation_dataset = combined_dataset.take(int(0.1 * len(combined_dataset)))

# history = model.fit(train_dataset, epochs=5, validation_data=validation_dataset)


In [ ]:
from tensorflow.keras.applications import VGG16

# Load the pre-trained VGG16 model
base_model = VGG16(weights='imagenet', include_top=False, input_shape=(256, 256, 3))

# Set the layers of the pre-trained model as non-trainable
for layer in base_model.layers:
    layer.trainable = False

# Create your custom classification layers on top
top_model = tf.keras.Sequential([
    tf.keras.layers.Flatten(input_shape=base_model.output_shape[1:]),
    tf.keras.layers.Dense(256, activation='relu'),
    tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Dense(1, activation='sigmoid')  # Binary classification
])

# Combine the base model and the custom top layer
model2 = tf.keras.Sequential([base_model, top_model])

# Compile the model
model2.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])


58889256/58889256 [==============================] - 0s 0us/step


In [ ]:
history2=model2.fit(train_dataset, epochs=5, validation_data=validation_dataset)

Epoch 1/5
2642/2642 [==============================] - 850s 256ms/step - loss: 0.6198 - accuracy: 0.7854 - val_loss: 0.8033 - val_accuracy: 0.7717
Epoch 2/5
2642/2642 [==============================] - 735s 219ms/step - loss: 0.4199 - accuracy: 0.7848 - val_loss: 0.7494 - val_accuracy: 0.8121
Epoch 3/5
2642/2642 [==============================] - 731s 219ms/step - loss: 0.4272 - accuracy: 0.7900 - val_loss: 1.0621 - val_accuracy: 0.8030
Epoch 4/5
2642/2642 [==============================] - 735s 219ms/step - loss: 0.4085 - accuracy: 0.8041 - val_loss: 1.6030 - val_accuracy: 0.7916
Epoch 5/5
   1/2642 [..............................] - ETA: 110:55:31 - loss: 0.2275 - accuracy: 0.8125

KeyboardInterrupt: ignored

In [ ]:
import tensorflow as tf
from tensorflow.keras.applications import ResNet50
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, GlobalAveragePooling2D, Dense, Dropout

# Load the ResNet50 model with pre-trained weights, excluding the top classification layers
base_model = ResNet50(weights='imagenet', include_top=False, input_shape=(256, 256, 3))

# Freeze the pre-trained layers
for layer in base_model.layers:
    layer.trainable = False

# Add custom classification layers on top of the ResNet50 feature extractor
x = base_model.output
x = GlobalAveragePooling2D()(x)
x = Dense(512, activation='relu')(x)
x = Dropout(0.5)(x)
predictions = Dense(1, activation='sigmoid')(x)  # Binary classification

# Create the custom model
custom_model = Model(inputs=base_model.input, outputs=predictions)

# Compile the model
custom_model.compile(optimizer='adam',
                     loss='binary_crossentropy',
                     metrics=['accuracy'])

# Print model summary
custom_model.summary()


Model: "model_1"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 input_3 (InputLayer)        [(None, 256, 256, 3)]        0         []                            
                                                                                                  
 conv1_pad (ZeroPadding2D)   (None, 262, 262, 3)          0         ['input_3[0][0]']             
                                                                                                  
 conv1_conv (Conv2D)         (None, 128, 128, 64)         9472      ['conv1_pad[0][0]']           
                                                                                                  
 conv1_bn (BatchNormalizati  (None, 128, 128, 64)         256       ['conv1_conv[0][0]']          
 on)                                                                                        

In [ ]:
history3=custom_model.fit(train_dataset, epochs=5, validation_data=validation_dataset)

Epoch 1/5
2642/2642 [==============================] - 619s 172ms/step - loss: 0.3154 - accuracy: 0.8744 - val_loss: 0.4535 - val_accuracy: 0.8217
Epoch 2/5
2642/2642 [==============================] - 580s 160ms/step - loss: 0.3042 - accuracy: 0.8768 - val_loss: 0.4481 - val_accuracy: 0.8209
Epoch 3/5
2642/2642 [==============================] - 621s 176ms/step - loss: 0.3022 - accuracy: 0.8793 - val_loss: 0.4539 - val_accuracy: 0.8242
Epoch 4/5
2642/2642 [==============================] - 624s 176ms/step - loss: 0.2959 - accuracy: 0.8800 - val_loss: 0.4506 - val_accuracy: 0.8269
Epoch 5/5
2642/2642 [==============================] - 576s 159ms/step - loss: 0.2925 - accuracy: 0.8774 - val_loss: 0.4323 - val_accuracy: 0.8285


In [ ]:
import matplotlib.pyplot as plt

def plot_training_history(history, label):
    # Plot training & validation accuracy values
    plt.plot(history.history['accuracy'])
    plt.plot(history.history['val_accuracy'])
    plt.title('Model Accuracy - ' + label)
    plt.ylabel('Accuracy')
    plt.xlabel('Epoch')
    plt.legend(['Train', 'Validation'], loc='upper left')
    plt.show()

    # Plot training & validation loss values
    plt.plot(history.history['loss'])
    plt.plot(history.history['val_loss'])
    plt.title('Model Loss - ' + label)
    plt.ylabel('Loss')
    plt.xlabel('Epoch')
    plt.legend(['Train', 'Validation'], loc='upper left')
    plt.show()

# Assuming history, history2, and history3 are available
plot_training_history(history, "History 1")
plot_training_history(history2, "History 2")
plot_training_history(history3, "History 3")
